page_dashboard/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name='index'),
]

page_friends/urls.py
from django.conf.urls import url
from .views import index, add_friend_post

urlpatterns = [
    url(r'^$', index, name="index"),
    url(r'^add_friend', add_friend_post, name='add_friend_post'),
]

page_profile/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name="index"),
]

page_status/urls.py
from django.conf.urls import url
from .views import index, add_status

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_status', add_status, name='add_status'),
]

tugas1/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import page_dashboard.urls as page_dashboard
import page_friends.urls as page_friends
import page_profile.urls as page_profile
import page_status.urls as page_status
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^dashboard/', include(page_dashboard, namespace='dashboard')),
    url(r'^friends/', include(page_friends, namespace='friends')),
    url(r'^profile/', include(page_profile, namespace='profile')),
    url(r'^status/', include(page_status, namespace='status')),
    url(r'^$', RedirectView.as_view(url='/status/', permanent='true'), name='index'),
]

page_dashboard/models.py
from django.db import models

# Create your models here.

page_friends/models.py
from django.db import models
import datetime


# Create your models here.
class Add_Friend(models.Model):
    name = models.CharField(max_length=27)
    url = models.URLField()
    date = models.DateTimeField(auto_now_add=True)

page_profile/models.py
from django.db import models
from datetime import date
import json


class SingleAccountObject:
    name = 'Kak Pewe'
    avatar = 'img/picture.jpg'
    birthday = date(2017, 8, 28)
    gender = 'L'
    expertises = json.dumps(["programming", "helping"])
    description = 'Official Mascot of PPW 2017'
    email = 'kak.pewe@ui.ac.id'


# Create your models here.
class Account(models.Model):
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female')
    )

    name = models.CharField(max_length=70)
    avatar = models.CharField(max_length=70)
    birthday = models.DateField()
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    expertises = models.CharField(max_length=200)
    description = models.TextField()
    email = models.EmailField()

page_status/models.py
from django.db import models


# Create your models here.
class Status(models.Model):
    status = models.TextField()
    status_date = models.DateTimeField(auto_now_add=True)

page_friends/forms.py
from django import forms


class Add_Friend_Form(forms.Form):
    error_messages = {
        'required': 'Please fill this',
    }
    attrs = {
        'class': 'form-control'
    }
    name = forms.CharField(label='Name', required=True, max_length=27, widget=forms.TextInput(attrs=attrs))
    url = forms.URLField(label='Url', required=True, widget=forms.URLInput(attrs=attrs))

page_status/forms.py
from django import forms


class Add_Status_Form(forms.Form):
    error_meesages = {
        'required': 'Tolong isi input ini',
    }

    status_attrs = {
        'class': 'form-control',
    }

    status = forms.CharField(label='', widget=forms.Textarea(attrs=status_attrs), required=True)

page_dashboard/views.py
from django.shortcuts import render
from page_friends.models import Add_Friend
from page_status.models import Status
from page_profile.models import Account, SingleAccountObject

# Create your views here.
response = {}
feed = Status.objects.all()
friends = Add_Friend.objects.all()
identity = Account.objects.all()


def index(request):
    response['identity'] = identity.get().name
    response['picture'] = identity.get().avatar
    if (feed != None):
        response['latest'] = feed.last()
    response['feed'] = feed.count()
    response['friends'] = friends.count()
    html = "page_dashboard/page_dashboard.html"
    return render(request, html, response)

page_friends/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Add_Friend_Form
from .models import Add_Friend

# Create your views here.
response = {}


def index(request):
    response['add_friend_form'] = Add_Friend_Form
    response['friends'] = Add_Friend.objects.all()
    html = 'page_friends/page_friends.html'
    return render(request, html, response)


def add_friend_post(request):
    form = Add_Friend_Form(request.POST or None)
    if (request.method == 'POST' and form.is_valid()):
        response['name'] = request.POST['name']
        response['url'] = request.POST['url']
        add_friend = Add_Friend(name=response['name'], url=response['url'])
        add_friend.save()
        return HttpResponseRedirect('/friends/')
    else:
        return HttpResponseRedirect('/friends/')

page_profile/views.py
import json
from django.shortcuts import render
from .models import Account


# Create your views here.
def index(request):
    response = {}
    html = 'page_profile/page_profile.html'

    response['profile'] = Account.objects.first()
    response['profile'].expertises = json.loads(response['profile'].expertises)

    return render(request, html, response)

page_status/views.py
import json
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Add_Status_Form
from .models import Status
from page_profile.models import Account

# Create your views here.
response = {}


def index(request):
    status = Status.objects.all()
    status = status[::-1]
    response['author'] = "Kelompok 12 PPW-A"
    response['status'] = status
    html = "page_status/page_status.html"
    response['status_form'] = Add_Status_Form
    response['profile'] = Account.objects.first()
    response['profile'].expertises = json.loads(response['profile'].expertises)
    return render(request, html, response)


def add_status(request):
    form = Add_Status_Form(request.POST or None)
    if (request.method == 'POST' and form.is_valid()):
        response['status'] = request.POST['status']
        status = Status(status=response['status'])
        status.save()
        return HttpResponseRedirect('/status/')
    else:
        return HttpResponseRedirect('/status/')

page_dashboard/templates/page_dashboard/page_dashboard.html
{% extends "tugas_1/layout/base.html" %}

{% load staticfiles %}
{% load static %}

{% block content %}
<section id="dashboard">
    <div class="container">
        <div class="row">
            <h1>Statistic</h1>
            <div class="col-md-6 col-md-offset-0">
                {% static "" as baseStaticUrl %}
                <img src="{{ baseStaticUrl }}{{ picture }}" class="img-responsive img-circle center-block"
                     alt="Ini Foto"
                     width=300
                     height=300
                />
            </div>
            <div class="col-md-6">
                <h2>{{ identity }}</h2>
                <div class="col-md-4 col-md-offset-0">
                    <p>Friends : {{ friends }}</p>
                </div>
                <div class="col-md-4 col-md-offset-0">
                    <p>Feed : {{ feed }}</p>
                </div>
                <div class="col-md-6 col-md-offset-0">
                    <div class="row">
                        <hr>
                        <div class="row-md-6">
                            <h3>Latest Status</h3>
                            <a id="name">{{ identity }}</a>
                            <p id="timedate">{{ latest.status_date|date:"l, j F Y, H:i" }}</p>
                            <p id="status">{{ latest.status }}</p>
                            <hr>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
</section>
{% endblock %}

page_friends/templates/page_friends/page_friends.html
{% extends "tugas_1/layout/base.html" %} {% block content %}

<section name="form">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <h1>Add Friend</h1>
            <form id="form" method="POST" action="{% url 'friends:add_friend_post' %}">
                {% csrf_token %} {{ add_friend_form }}
                <br>
                <button type="submit" class="btn btn-default">Add Friend</button>
            </form>
        </div>
    </div>
</section>

<section name="list-friend">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <h1>List Friend</h1>
            <table class="table">
                <tbody>
                {% for i in friends %}
                <tr>
                    <td> {{i.name}}</td>
                    <td> {{i.url}}</td>
                    <td> Added {{i.date}}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</section>

{% endblock %}

page_profile/templates/page_profile/page_profile.html
{% extends "tugas_1/layout/base.html" %} {% load staticfiles %} {% load static %} {% block content %}

<section>
    <div class="container">
        <div class="row">
            <div class="center-block">
                {% static "" as baseStaticUrl %}
                <img src="{{ baseStaticUrl }}{{ profile.avatar }}" class="img-responsive img-circle center-block"
                     width="200px">
                <h1 class="text-center"> {{ profile.name }} </h1>
            </div>
            <div class="col-md-2 col-md-offset-4">
                Birthday <br> Gender <br> Expertise <br> Description <br> Email <br>
            </div>
            <div class="col-md-4">
                {{ profile.birthday|date:"M d, Y" }}
                <br> {{ profile.gender }}
                <br> {% for expertise in profile.expertises %}
                <span class="badge badge-pill"> {{ expertise }} </span> {% endfor %}
                <br> {{ profile.description }}
                <br> {{ profile.email }}
            </div>
        </div>
    </div>
</section>

{% endblock %}

page_status/templates/page_status/page_status.html
{% extends "tugas_1/layout/base.html" %} {% load staticfiles %} {% load static %} {% block content %}
<section id="input-status">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <h3 id="title-status">Update Your Status</h3>
            <form id="form" method="POST" action="{% url 'status:add_status' %}">
                {% csrf_token %} {{status_form}}
                <input id="submit" type="submit" class="btn btn-default pull-right" value="Post">
            </form>
        </div>
    </div>
</section>

<section id="all-status">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            {% if status %}{% for data in status %} {% static "" as baseStaticUrl %}
            <div class="col-md-2 col-md-offset-1"><img src="{{ baseStaticUrl }}{{ profile.avatar }}"
                                                       class="img-responsive img-circle center-block" width="50px">
            </div>
            <div class="col-md-8">
                <a id="name" href="{% url 'profile:index' %}">{{profile.name}}</a>
                <p id="timedate">{{data.status_date|date:"l, j F Y, H:i"}}</p>
                <p id="status">{{data.status}}</p>
                <hr>
            </div>
            <br> {% endfor %} {% endif %}
        </div>
    </div>
</section>

{% endblock %}

tugas1/templates/tugas_1/layout/base.html
{% load staticfiles %} {% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Tugas 1 PPW Kelas A Kelompok 12">
    <meta name="author" content="{{author}}">
    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <!--
	<link rel="stylesheet" type="text/css" href="{% static 'css/lab_5.css' %}" />
    -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/tugas1.css' %}"/>
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
    <title>
        {% block title %} Kelompok 12 {% endblock %}
    </title>
</head>

<body>
<header>
    {% include "tugas_1/partials/header.html" %}
</header>
<content class="content">
    {% block content %}
    <!-- content goes here -->
    {% endblock %}
</content>
<footer class="footer">
    <!-- TODO Block Footer dan include footer.html -->
    {% block footer %} {% include "tugas_1/partials/footer.html" %} {% endblock %}
</footer>

<!-- Jquery n Bootstrap Script -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script type="application/javascript"
        src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>

</html>

tugas1/templates/tugas_1/partials/footer.html
<p>&copy; PPW-A Kelompok 12</p>

tugas1/templates/tugas_1/partials/header.html
<nav class="nav navbar-default navbar-fixed-top">
    <div class="container-fluid">
        <div id="navbrand" class="navbar-header">
            <a class="navbar-brand" href="{% url 'status:index' %}">Ling-in</a>
            <button class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar"></button><span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span>
            <span class="icon-bar"></span>
            </button>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'status:index' %}">Status</a></li>
                <li><a href="{% url 'profile:index' %}">Profile</a></li>
                <li><a href="{% url 'friends:index' %}">Friends</a></li>
                <li><a href="{% url 'dashboard:index' %}">Stats</a></li>
            </ul>
        </div>
    </div>
</nav>